In [114]:
from array import array
from numpy import *
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import linear_model

In [115]:
df = pd.read_csv('Housing.csv')
df

area  bedrooms  age   price
0  2600       2.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

Preprocessing to handle missing values

In [116]:
import math
med_bedrooms = math.floor(df.bedrooms.median())     #keeping integer value 3 than 3.5
med_bedrooms

3

In [117]:
df.bedrooms = df.bedrooms.fillna(med_bedrooms)        #fill NaN value
df.bedrooms

0    2.0
1    4.0
2    3.0
3    3.0
4    5.0
Name: bedrooms, dtype: float64

In [118]:
df

area  bedrooms  age   price
0  2600       2.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

Train the model

In [119]:
reg = linear_model.LinearRegression()       #create linear regression class object
reg.fit(df[['area', 'bedrooms', 'age']], df.price)

LinearRegression()

In [120]:
reg.coef_

array([   177.0857453 , -44705.86107091,  -8253.25615051])

In [121]:
reg.intercept_

337367.94500723557

Calculate the price with m1, m2, m3, and b

1. 3000 sq ft, 3 bedrooms, 40 yr old
2. 2500 sq ft, 4 bedrooms, 5 yr old

In [122]:
reg.predict([[3000, 3, 40]])

c:\Users\Rituparna Addy\miniconda3\envs\datascience\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([404377.35166425])

In [123]:
reg.predict([[3000, 4, 15]])        #Actual

c:\Users\Rituparna Addy\miniconda3\envs\datascience\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([566002.89435601])

In [124]:
177.0857453*3000 + (-44705.86107091)*3 + (-8253.25615051)*40 + 337367.94500723557

404377.3516741056

2. 2500 sq ft, 4 bedrooms, 5 yr old

In [125]:
reg.predict([[2500, 4, 5]])

c:\Users\Rituparna Addy\miniconda3\envs\datascience\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([559992.58321274])

Predict salaries for candidates:
1. 2 yr exp, 9 test score, 6 interview score
2. 12 yr exp, 10 test score, 10 interview score

In [126]:
d = pd.read_csv('Salary.csv')
d

experience  test_score(out of 10)  interview_score(out of 10)  salary
0        NaN                    8.0                           9   50000
1        NaN                    8.0                           6   45000
2       five                    6.0                           7   60000
3        two                   10.0                          10   65000
4      seven                    9.0                           6   70000
5      three                    7.0                          10   62000
6        ten                    NaN                           7   72000
7     eleven                    7.0                           8   80000

In [127]:
from word2number import w2n

In [128]:
d.experience = d.experience.fillna('zero')
d   

experience  test_score(out of 10)  interview_score(out of 10)  salary
0       zero                    8.0                           9   50000
1       zero                    8.0                           6   45000
2       five                    6.0                           7   60000
3        two                   10.0                          10   65000
4      seven                    9.0                           6   70000
5      three                    7.0                          10   62000
6        ten                    NaN                           7   72000
7     eleven                    7.0                           8   80000

In [129]:
d.experience = d.experience.apply(w2n.word_to_num)
d

experience  test_score(out of 10)  interview_score(out of 10)  salary
0           0                    8.0                           9   50000
1           0                    8.0                           6   45000
2           5                    6.0                           7   60000
3           2                   10.0                          10   65000
4           7                    9.0                           6   70000
5           3                    7.0                          10   62000
6          10                    NaN                           7   72000
7          11                    7.0                           8   80000

In [130]:
import math
mean_test = math.floor(d['test_score(out of 10)'].mean())   
mean_test

7

In [131]:
d['test_score(out of 10)'] = d['test_score(out of 10)'].fillna(mean_test)        #fill NaN value
d['test_score(out of 10)']

0     8.0
1     8.0
2     6.0
3    10.0
4     9.0
5     7.0
6     7.0
7     7.0
Name: test_score(out of 10), dtype: float64

In [132]:
reg_model = linear_model.LinearRegression() 
reg_model.fit(d[['experience', 'test_score(out of 10)', 'interview_score(out of 10)']], d.salary)

LinearRegression()

In [133]:
reg_model.coef_

array([2922.26901502, 2221.30909959, 2147.48256637])

In [134]:
reg_model.intercept_

14992.65144669314

In [136]:
reg_model.predict([[2,9,6]])

c:\Users\Rituparna Addy\miniconda3\envs\datascience\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53713.86677124])

In [137]:
reg_model.predict([[12,10,10]])

c:\Users\Rituparna Addy\miniconda3\envs\datascience\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([93747.79628651])